<?php
	include('../config/config.php');
	include('../config/functions.php');
	include('header/head.php');
	include('header/asideMenuAdmin.php');
	include('data/courseOption.php');
	include('data/moduleData.php');
	
	if(logged_in()){
		
	}else{
		header('Location: adminLogin.php');
	}
	
?>
<aside class="main-sidebar">

    <section class="sidebar">

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header">USER MANAGEMENT</li>
		<li class="treeview">
			<a href="#"><i class="fa fa-book"></i> <span>Student Management</span> <i class="fa fa-angle-left pull-right"></i></a>
			<ul class="treeview-menu">
				<li><a href="admin.php"><i class="fa fa-file-o"></i> <span>Bachelor Degree</span></a></li>
				<li><a href="adminStudentDiploma.php"><i class="fa fa-file-o"></i> <span>Ordinary Diploma</span></a></li>
			</ul>
		</li>
		<li><a href="adminLecturer.php"><i class="fa fa-book"></i> <span>Lecturer Management</span></a></li>
		<li><a href="adminStaff.php"><i class="fa fa-book"></i> <span>Staff Management</span></a></li>
		<li class="active treeview"><a href="#"><i class="fa fa-book"></i> <span>Add Module</span> <i class="fa fa-angle-left pull-right"></i></a>
			<ul class="treeview-menu">
				<li class="active"><a href="adminAddModuleBachelor.php"><i class="fa fa-circle-o"></i> <span>Bachelor Degree</span></a></li>
				<li><a href="adminAddModuleDiploma.php"><i class="fa fa-circle-o"></i> <span>Ordinary Diploma</span></a></li>
			</ul>
		</li>
		<li><a href="adminAddCourse.php"><i class="fa fa-book"></i> <span>Add Course</span></a></li>
		<li><a href="uploadImages.php"><i class="fa fa-circle-o"></i> <span>Upload Images</span></a></li>
		<li><a href="adminProfile.php"><i class="fa fa-user"></i> <span>Profile Settings</span></a></li>
		<li><a href="logout.php"><i class="fa fa-user"></i> <span>Sign Out</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Module Management<small></small></h1>
      <ol class="breadcrumb">
        <li><a href="admin.php"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>Add Module</li>
		<li class="active">Bachelor Degree</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
		<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<?php 
			if(isset($success)){
				if($success[1] == 'success'){
					if($success[0] > 1){
						$s = 's'; $are = 'are'; $the = '';
					}else{
						$s = ''; $are = 'is'; $the = 'A';
					}
					echo "<div class='callout callout-success displaySms'>
							<h4>Successfully !</h4>
							<p>".$the." subject".$s." ".$are." successful added</p>
						</div>";
				}else if($success[5] == 'fail'){
					echo "<div class='callout callout-danger displaySms'>
						<h4>ERROR !</h4>
						<p>Sorry something went wrong, try again.</p>
					</div>";
				}else if($success[2] == 'empty'){
					echo "<div class='callout callout-danger displaySms'>
						<h4>ERROR !</h4>
						<p>Please Fill the field.</p>
					</div>";
				}else if($success[3] == 'invalid'){
					echo "<div class='callout callout-danger displaySms'>
						<h4>ERROR !</h4>
						<p>Please make sure:- code contains letters and numbers, module title contains letters only and credit contains number only.</p>
					</div>";
				}else if($success[4] == 'digit_error'){
					echo "<div class='callout callout-danger displaySms'>
						<h4>ERROR !</h4>
						<p>Credit must be two digit number.</p>
					</div>";
				}
				if($success[6] == 'no_year'){
					echo "<div class='callout callout-danger displaySms'>
							<h4>ERROR !</h4>
							<p>Please select a year.</p>
						</div>";
				}
				if($success[7] == 'no_semester'){
					echo "<div class='callout callout-danger displaySms'>
							<h4>ERROR !</h4>
							<p>Please select a semester.</p>
						</div>";
				}
				if($success[8] == 'no_course'){
					echo "<div class='callout callout-danger displaySms'>
							<h4>ERROR !</h4>
							<p>Please select a course.</p>
						</div>";
				}
				if($success[9] == 'duplicate'){
					echo "<div class='callout callout-danger displaySms'>
							<h4>ERROR !</h4>
							<p>";
						for($i=0;$i<count($success_f);$i++){	
							echo "<b> Code: ".replaceUnderscoreWithSpace($success_f[$i])." Module: ".replaceUnderscoreWithSpace($success_m[$i])." Credit: ".$success_s[$i]."<br></b>";
						}
					echo	" seems to be already uploaded.</p>
						</div>";
				}
			}
			?>
		</div>
		<div class="col-md-3"></div>
	</div>
		<div class="box box-primary box-height" style="margin-bottom:0;">
			<form method="post" enctype="multipart/form-data">
			<div class="row" style="margin:2% auto;">
				<div class="col-md-3">
					<div class="form-group">
						<label>Year</label><br>
						<select name="year" class="form-control select2"> 
						<?php
							if(isset($_POST['year']) && !empty($_POST['year'])){
								echo '<option selected="selected" value="'.$_POST['year'] .'">'.$_POST['year'].'</option>';
							}else{
								echo '<option selected="selected" value="">Select a year</option>';
							}
						?>
						  <option value="first">First</option>
						  <option value="second">Second</option>
						  <option value="third">Third</option>
						  <option value="forth">Forth</option>
						</select>
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<label>Semester</label><br>
						<select name="semester" class="form-control select2">
						<?php
							if(isset($_POST['semester']) && !empty($_POST['semester'])){
								echo '<option selected="selected" value="'.$_POST['semester'] .'">'.$_POST['semester'].'</option>';
							}else{
								echo '<option selected="selected" value="">Select a semester</option>';
							}
						?>
						  <option value="first">First</option>
						  <option value="second">Second</option>
						</select>
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<label>Course</label><br>
						<select name="course" class="form-control select2">
							<?php
								if(isset($_POST['course']) && !empty($_POST['course'])){
									echo '<option selected="selected">'.$_POST['course'].'</option>';
								}else{
									echo '<option selected="selected" value="">Select a Course</option>';
								}
								if(isset($course1)){
									foreach($course1 as $c){
											echo  '<option>'.$c.'</option>';
									}
								}
							?>	
						</select>
					</div>
				</div>
			</div>
			
			<!--start table -->
			<div class="row" style="margin:2% auto;">
				<div class="col-md-12">
					<div class="box-body">
						<table id="StudentMgt" class="table table-bordered table-hover">
							<thead>
								<tr>
								  <th>S/No</th>
								  <th>Code</th>
								  <th>Module Title</th>
								  <th>Credit</th>
								</tr>
							</thead>
							<tbody>
								<tr><td>1</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][0];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][0];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][0];}?>"></td></tr>
								<tr><td>2</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][1];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][1];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][1];}?>"></td></tr>
								<tr><td>3</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][2];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][2];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][2];}?>"></td></tr>
								<tr><td>4</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][3];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][3];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][3];}?>"></td></tr>
								<tr><td>5</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][4];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][4];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][4];}?>"></td></tr>
								<tr><td>6</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][5];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][5];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][5];}?>"></td></tr>
								<tr><td>7</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][6];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][6];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][6];}?>"></td></tr>
								<tr><td>8</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][7];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][7];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][7];}?>"></td></tr>
								<tr><td>9</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][8];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][8];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][8];}?>"></td></tr>
								<tr><td>10</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][9];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][9];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][9];}?>"></td></tr>
								<tr><td>11</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][10];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][10];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][10];}?>"></td></tr>
								<tr><td>12</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][11];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][11];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][11];}?>"></td></tr>
								<tr><td>13</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][12];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][12];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][12];}?>"></td></tr>
								<tr><td>14</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][13];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][13];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][13];}?>"></td></tr>
								<tr><td>15</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][14];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][14];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][14];}?>"></td></tr>
								<tr><td>16</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][15];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][15];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][15];}?>"></td></tr>
								<tr><td>17</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][16];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][16];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][16];}?>"></td></tr>
								<tr><td>18</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][17];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][17];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][17];}?>"></td></tr>
								<tr><td>19</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][18];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][18];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][18];}?>"></td></tr>
								<tr><td>20</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][19];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][19];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][19];}?>"></td></tr>
								<tr><td>21</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][20];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][20];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][20];}?>"></td></tr>
								<tr><td>22</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][21];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][21];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][21];}?>"></td></tr>
								<tr><td>23</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][22];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][22];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][22];}?>"></td></tr>
								<tr><td>24</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][23];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][23];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][23];}?>"></td></tr>
								<tr><td>25</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][24];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][24];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][24];}?>"></td></tr>
								<tr><td>26</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][25];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][25];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][25];}?>"></td></tr>
								<tr><td>27</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][26];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][26];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][26];}?>"></td></tr>
								<tr><td>28</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][27];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][27];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][27];}?>"></td></tr>
								<tr><td>29</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][28];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][28];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][28];}?>"></td></tr>
								<tr><td>30</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][29];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][29];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][29];}?>"></td></tr>
								<tr><td>31</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][30];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][30];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][30];}?>"></td></tr>
								<tr><td>32</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][31];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][31];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][31];}?>"></td></tr>
								<tr><td>33</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][32];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][32];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][32];}?>"></td></tr>
								<tr><td>34</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][33];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][33];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][33];}?>"></td></tr>
								<tr><td>35</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][34];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][34];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][34];}?>"></td></tr>
								<tr><td>36</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][35];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][35];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][35];}?>"></td></tr>
								<tr><td>37</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][36];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][36];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][36];}?>"></td></tr>
								<tr><td>38</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][37];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][37];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][37];}?>"></td></tr>
								<tr><td>39</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][38];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][38];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][38];}?>"></td></tr>
								<tr><td>40</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][39];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][39];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][39];}?>"></td></tr>
								<tr><td>41</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][40];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][40];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][40];}?>"></td></tr>
								<tr><td>42</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][41];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][41];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][41];}?>"></td></tr>
								<tr><td>43</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][42];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][42];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][42];}?>"></td></tr>
								<tr><td>44</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][43];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][43];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][43];}?>"></td></tr>
								<tr><td>45</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][44];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][44];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][44];}?>"></td></tr>
								<tr><td>46</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][45];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][45];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][45];}?>"></td></tr>
								<tr><td>47</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][46];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][46];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][46];}?>"></td></tr>
								<tr><td>48</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][47];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][47];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][47];}?>"></td></tr>
								<tr><td>49</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][48];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][48];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][48];}?>"></td></tr>
								<tr><td>50</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][49];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][49];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][49];}?>"></td></tr>
								<tr><td>51</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][50];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][50];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][50];}?>"></td></tr>
								<tr><td>52</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][51];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][51];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][51];}?>"></td></tr>
								<tr><td>53</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][52];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][52];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][52];}?>"></td></tr>
								<tr><td>54</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][53];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][53];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][53];}?>"></td></tr>
								<tr><td>55</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][54];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][54];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][54];}?>"></td></tr>
								<tr><td>56</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][55];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][55];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][55];}?>"></td></tr>
								<tr><td>57</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][56];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][56];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][56];}?>"></td></tr>
								<tr><td>58</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][57];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][57];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][57];}?>"></td></tr>
								<tr><td>59</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][58];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][58];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][58];}?>"></td></tr>
								<tr><td>60</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][59];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][59];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][59];}?>"></td></tr>
								<tr><td>61</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][60];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][60];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][60];}?>"></td></tr>
								<tr><td>62</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][61];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][61];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][61];}?>"></td></tr>
								<tr><td>63</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][62];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][62];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][62];}?>"></td></tr>
								<tr><td>64</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][63];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][63];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][63];}?>"></td></tr>
								<tr><td>65</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][64];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][64];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][64];}?>"></td></tr>
								<tr><td>66</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][65];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][65];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][65];}?>"></td></tr>
								<tr><td>67</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][66];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][66];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][66];}?>"></td></tr>
								<tr><td>68</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][67];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][67];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][67];}?>"></td></tr>
								<tr><td>69</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][68];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][68];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][68];}?>"></td></tr>
								<tr><td>70</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][69];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][69];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][69];}?>"></td></tr>
								<tr><td>71</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][70];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][70];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][70];}?>"></td></tr>
								<tr><td>72</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][71];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][71];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][71];}?>"></td></tr>
								<tr><td>73</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][72];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][72];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][72];}?>"></td></tr>
								<tr><td>74</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][73];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][73];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][73];}?>"></td></tr>
								<tr><td>75</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][74];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][74];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][74];}?>"></td></tr>
								<tr><td>76</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][75];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][75];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][75];}?>"></td></tr>
								<tr><td>77</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][76];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][76];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][76];}?>"></td></tr>
								<tr><td>78</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][77];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][77];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][77];}?>"></td></tr>
								<tr><td>79</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][78];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][78];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][78];}?>"></td></tr>
								<tr><td>80</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][79];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][79];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][79];}?>"></td></tr>
								<tr><td>81</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][80];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][80];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][80];}?>"></td></tr>
								<tr><td>82</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][81];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][81];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][81];}?>"></td></tr>
								<tr><td>83</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][82];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][82];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][82];}?>"></td></tr>
								<tr><td>84</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][83];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][83];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][83];}?>"></td></tr>
								<tr><td>85</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][84];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][84];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][84];}?>"></td></tr>
								<tr><td>86</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][85];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][85];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][85];}?>"></td></tr>
								<tr><td>87</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][86];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][86];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][86];}?>"></td></tr>
								<tr><td>88</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][87];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][87];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][87];}?>"></td></tr>
								<tr><td>89</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][88];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][88];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][88];}?>"></td></tr>
								<tr><td>90</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][89];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][89];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][89];}?>"></td></tr>
								<tr><td>91</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][90];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][90];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][90];}?>"></td></tr>
								<tr><td>92</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][91];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][91];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][91];}?>"></td></tr>
								<tr><td>93</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][92];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][92];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][92];}?>"></td></tr>
								<tr><td>94</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][93];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][93];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][93];}?>"></td></tr>
								<tr><td>95</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][94];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][94];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][94];}?>"></td></tr>
								<tr><td>96</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][95];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][95];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][95];}?>"></td></tr>
								<tr><td>97</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][96];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][96];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][96];}?>"></td></tr>
								<tr><td>98</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][97];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][97];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][97];}?>"></td></tr>
								<tr><td>99</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][98];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][98];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][98];}?>"></td></tr>
								<tr><td>100</td> <td><input type="text" class="form-control" name="code[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['code'][99];}?>"></td> <td><input type="text" class="form-control" name="module_title[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['module_title'][99];}?>"></td> <td><input type="text" class="form-control" name="credit[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8]) || isset($success[9])){echo $_POST['credit'][99];}?>"></td></tr>
								
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<!--end table -->
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-3">
					<div class="form-group">
						<label></label><br>
						<button type="submit" name="sv_modules_b" class="btn btn-primary">Save</button>
					</div>
				</div>
			</div>
			</form>
		</div>

    </section>
  </div>

<?php 
	include('footer/footer.php');
	include('footer/helpAdmin.php');
	include('footer/js.php');
?>