<?php
	include('../config/config.php');
	include('../config/functions.php');
	include('header/head.php');
	include('header/asideMenuAdmin.php');
	include('data/courseOptionDiploma.php');
	include('data/stDiploma.php');
	
	if(logged_in()){
		
	}else{
		header('Location: adminLogin.php');
	}
	
?>
<aside class="main-sidebar">

    <section class="sidebar">

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header">USER MANAGEMENT</li>
		<li class="active treeview">
			<a href="#"><i class="fa fa-book"></i> <span>Student Management</span> <i class="fa fa-angle-left pull-right"></i></a>
			<ul class="treeview-menu">
				<li><a href="admin.php"><i class="fa fa-file-o"></i> <span>Bachelor Degree</span></a></li>
				<li class="active"><a href="adminStudentDiploma.php"><i class="fa fa-file-o"></i> <span>Ordinary Diploma</span></a></li>
			</ul>
		</li>
		<li><a href="adminLecturer.php"><i class="fa fa-book"></i> <span>Lecturer Management</span></a></li>
		<li><a href="adminStaff.php"><i class="fa fa-book"></i> <span>Staff Management</span></a></li>
		<li class="treeview"><a href="#"><i class="fa fa-book"></i> <span>Add Module</span> <i class="fa fa-angle-left pull-right"></i></a>
			<ul class="treeview-menu">
				<li><a href="adminAddModuleBachelor.php"><i class="fa fa-circle-o"></i> <span>Bachelor Degree</span></a></li>
				<li><a href="adminAddModuleDiploma.php"><i class="fa fa-circle-o"></i> <span>Ordinary Diploma</span></a></li>
			</ul>
		</li>
		<li><a href="adminAddCourse.php"><i class="fa fa-book"></i> <span>Add Course</span></a></li>
		<li><a href="uploadImages.php"><i class="fa fa-circle-o"></i> <span>Upload Images</span></a></li>
		<li><a href="adminProfile.php"><i class="fa fa-user"></i> <span>Profile Settings</span></a></li>
		<li><a href="logout.php"><i class="fa fa-user"></i> <span>Sign Out</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Student Management<small></small></h1>
      <ol class="breadcrumb">
        <li><a href="admin.php"><i class="fa fa-dashboard"></i> Home</a></li>
		<li>Student Management</li>
		<li class="active">Ordinary Diploma</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<?php 
			if(isset($success)){
					if($success[1] == 'success'){
						echo "<div class='callout callout-success displaySms'>
								<h4>Successfully !</h4>
								<p>".$success[0]." Successful Inserted.</p>
							</div>";
					}
					if($success[2] == 'fail'){
						echo "<div class='callout callout-danger displaySms'>
								<h4>ERROR !</h4>
								<p>".$success[0]." failed. Sorry something went wrong, try to insert again.</p>
							</div>";
					}
					if($success[3] == 'empty'){
						echo "<div class='callout callout-danger displaySms'>
								<h4>ERROR !</h4>
								<p>Please Fill the field.</p>
							</div>";
					}
					if($success[4] == 'invalid'){
						echo "<div class='callout callout-danger displaySms'>
								<h4>ERROR !</h4>
								<p>Letters Only and No space.</p>
							</div>";
					}
					if($success[5] == 'duplicate'){
						echo "<div class='callout callout-danger displaySms'>
								<h4>ERROR !</h4>
								<p>";
							for($i=0;$i<count($success_f);$i++){	
								echo "<b>".$success_f[$i]." ".$success_m[$i]." ".$success_s[$i]."<br></b>";
							}
						echo	" already registered.</p>
							</div>";
					}
					if($success[6] == 'no_year'){
						echo "<div class='callout callout-danger displaySms'>
								<h4>ERROR !</h4>
								<p>Please select a year.</p>
							</div>";
					}
					if($success[7] == 'no_semester'){
						echo "<div class='callout callout-danger displaySms'>
								<h4>ERROR !</h4>
								<p>Please select a semester.</p>
							</div>";
					}
					if($success[8] == 'no_course'){
						echo "<div class='callout callout-danger displaySms'>
								<h4>ERROR !</h4>
								<p>Please select a course.</p>
							</div>";
					}
				}
			?>
		</div>
		<div class="col-md-3"></div>
	</div>
		<div class="row">
			
			<div class="col-md-12">
				<div class="nav-tabs-custom">
						<ul class="nav nav-tabs">
						  <li class="active"><a href="#p_info" data-toggle="tab">Entries</a></li>
						</ul>
					<div class="tab-content box-height-tab">
						 <div class="active tab-pane" id="p_info">
							<form method="post" enctype="multipart/form-data">
								<div class="row" style="margin:2% auto;">
									<div class="col-md-3">
										<div class="form-group">
											<label>Year</label><br>
											<select name="year" class="form-control select2"> 
						<?php
							if(isset($_POST['year']) && !empty($_POST['year'])){
								echo '<option selected="selected" value="'.$_POST['year'] .'">'.$_POST['year'].'</option>';
							}else{
								echo '<option selected="selected" value="">Select a year</option>';
							}
						?>
											  <option value="first">First</option>
											  <option value="second">Second</option>
											  <option value="third">Third</option>
											</select>
										</div>
									</div>
									<div class="col-md-3">
										<div class="form-group">
											<label>Semester</label><br>
											<select name="semester" class="form-control select2">
						<?php
							if(isset($_POST['semester']) && !empty($_POST['semester'])){
								echo '<option selected="selected" value="'.$_POST['semester'] .'">'.$_POST['semester'].'</option>';
							}else{
								echo '<option selected="selected" value="">Select a semester</option>';
							}
						?>
											  <option value="first">First</option>
											  <option value="second">Second</option>
											</select>
										</div>
									</div>
									<div class="col-md-3">
										<div class="form-group course">
											<label>Course</label>
												<select name="course" class="form-control select2">
						<?php
									if(isset($_POST['course']) && !empty($_POST['course'])){
										echo '<option selected="selected">'.$_POST['course'].'</option>';
									}else{
										echo '<option selected="selected" value="">Select a Course</option>';
									}
									if(isset($course1)){
										foreach($course1 as $c){
												echo  '<option>'.$c.'</option>';
										}
									}
						?>	
												</select>
										</div>
									</div>
								</div>
								
								<!--start table -->
								<div class="row" style="margin:2% auto;">
									<div class="col-md-12">
										<div class="box-body">
											<table id="StudentMgt" class="table table-bordered table-hover">
												<thead>
													<tr>
													  <th>S/No</th>
													  <th>First Name</th>
													  <th>Middle Name</th>
													  <th>Surname</th>
													</tr>
												</thead>
												<tbody>
													<tr><td>1</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][0];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][0];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][0];}?>"></td></tr>
													<tr><td>2</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][1];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][1];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][1];}?>"></td></tr>
													<tr><td>3</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][2];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][2];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][2];}?>"></td></tr>
													<tr><td>4</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][3];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][3];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][3];}?>"></td></tr>
													<tr><td>5</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][4];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][4];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][4];}?>"></td></tr>
													<tr><td>6</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][5];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][5];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][5];}?>"></td></tr>
													<tr><td>7</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][6];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][6];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][6];}?>"></td></tr>
													<tr><td>8</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][7];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][7];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][7];}?>"></td></tr>
													<tr><td>9</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][8];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][8];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][8];}?>"></td></tr>
													<tr><td>10</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][9];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][9];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][9];}?>"></td></tr>
													<tr><td>11</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][10];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][10];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][10];}?>"></td></tr>
													<tr><td>12</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][11];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][11];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][11];}?>"></td></tr>
													<tr><td>13</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][12];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][12];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][12];}?>"></td></tr>
													<tr><td>14</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][13];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][13];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][13];}?>"></td></tr>
													<tr><td>15</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][14];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][14];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][14];}?>"></td></tr>
													<tr><td>16</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][15];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][15];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][15];}?>"></td></tr>
													<tr><td>17</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][16];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][16];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][16];}?>"></td></tr>
													<tr><td>18</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][17];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][17];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][17];}?>"></td></tr>
													<tr><td>19</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][18];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][18];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][18];}?>"></td></tr>
													<tr><td>20</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][19];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][19];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][19];}?>"></td></tr>
													<tr><td>21</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][20];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][20];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][20];}?>"></td></tr>
													<tr><td>22</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][21];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][21];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][21];}?>"></td></tr>
													<tr><td>23</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][22];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][22];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][22];}?>"></td></tr>
													<tr><td>24</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][23];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][23];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][23];}?>"></td></tr>
													<tr><td>25</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][24];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][24];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][24];}?>"></td></tr>
													<tr><td>26</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][25];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][25];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][25];}?>"></td></tr>
													<tr><td>27</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][26];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][26];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][26];}?>"></td></tr>
													<tr><td>28</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][27];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][27];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][27];}?>"></td></tr>
													<tr><td>29</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][28];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][28];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][28];}?>"></td></tr>
													<tr><td>30</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][29];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][29];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][29];}?>"></td></tr>
													<tr><td>31</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][30];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][30];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][30];}?>"></td></tr>
													<tr><td>32</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][31];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][31];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][31];}?>"></td></tr>
													<tr><td>33</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][32];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][32];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][32];}?>"></td></tr>
													<tr><td>34</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][33];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][33];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][33];}?>"></td></tr>
													<tr><td>35</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][34];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][34];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][34];}?>"></td></tr>
													<tr><td>36</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][35];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][35];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][35];}?>"></td></tr>
													<tr><td>37</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][36];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][36];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][36];}?>"></td></tr>
													<tr><td>38</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][37];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][37];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][37];}?>"></td></tr>
													<tr><td>39</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][38];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][38];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][38];}?>"></td></tr>
													<tr><td>40</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][39];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][39];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][39];}?>"></td></tr>
													<tr><td>41</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][40];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][40];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][40];}?>"></td></tr>
													<tr><td>42</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][41];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][41];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][41];}?>"></td></tr>
													<tr><td>43</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][42];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][42];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][42];}?>"></td></tr>
													<tr><td>44</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][43];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][43];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][43];}?>"></td></tr>
													<tr><td>45</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][44];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][44];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][44];}?>"></td></tr>
													<tr><td>46</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][45];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][45];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][45];}?>"></td></tr>
													<tr><td>47</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][46];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][46];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][46];}?>"></td></tr>
													<tr><td>48</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][47];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][47];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][47];}?>"></td></tr>
													<tr><td>49</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][48];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][48];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][48];}?>"></td></tr>
													<tr><td>50</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][49];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][49];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][49];}?>"></td></tr>
													<tr><td>51</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][50];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][50];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][50];}?>"></td></tr>
													<tr><td>52</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][51];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][51];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][51];}?>"></td></tr>
													<tr><td>53</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][52];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][52];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][52];}?>"></td></tr>
													<tr><td>54</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][53];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][53];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][53];}?>"></td></tr>
													<tr><td>55</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][54];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][54];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][54];}?>"></td></tr>
													<tr><td>56</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][55];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][55];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][55];}?>"></td></tr>
													<tr><td>57</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][56];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][56];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][56];}?>"></td></tr>
													<tr><td>58</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][57];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][57];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][57];}?>"></td></tr>
													<tr><td>59</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][58];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][58];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][58];}?>"></td></tr>
													<tr><td>60</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][59];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][59];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][59];}?>"></td></tr>
													<tr><td>61</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][60];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][60];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][60];}?>"></td></tr>
													<tr><td>62</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][61];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][61];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][61];}?>"></td></tr>
													<tr><td>63</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][62];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][62];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][62];}?>"></td></tr>
													<tr><td>64</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][63];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][63];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][63];}?>"></td></tr>
													<tr><td>65</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][64];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][64];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][64];}?>"></td></tr>
													<tr><td>66</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][65];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][65];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][65];}?>"></td></tr>
													<tr><td>67</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][66];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][66];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][66];}?>"></td></tr>
													<tr><td>68</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][67];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][67];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][67];}?>"></td></tr>
													<tr><td>69</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][68];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][68];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][68];}?>"></td></tr>
													<tr><td>70</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][69];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][69];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][69];}?>"></td></tr>
													<tr><td>71</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][70];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][70];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][70];}?>"></td></tr>
													<tr><td>72</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][71];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][71];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][71];}?>"></td></tr>
													<tr><td>73</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][72];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][72];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][72];}?>"></td></tr>
													<tr><td>74</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][73];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][73];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][73];}?>"></td></tr>
													<tr><td>75</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][74];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][74];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][74];}?>"></td></tr>
													<tr><td>76</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][75];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][75];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][75];}?>"></td></tr>
													<tr><td>77</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][76];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][76];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][76];}?>"></td></tr>
													<tr><td>78</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][77];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][77];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][77];}?>"></td></tr>
													<tr><td>79</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][78];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][78];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][78];}?>"></td></tr>
													<tr><td>80</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][79];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][79];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][79];}?>"></td></tr>
													<tr><td>81</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][80];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][80];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][80];}?>"></td></tr>
													<tr><td>82</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][81];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][81];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][81];}?>"></td></tr>
													<tr><td>83</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][82];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][82];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][82];}?>"></td></tr>
													<tr><td>84</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][83];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][83];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][83];}?>"></td></tr>
													<tr><td>85</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][84];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][84];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][84];}?>"></td></tr>
													<tr><td>86</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][85];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][85];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][85];}?>"></td></tr>
													<tr><td>87</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][86];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][86];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][86];}?>"></td></tr>
													<tr><td>88</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][87];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][87];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][87];}?>"></td></tr>
													<tr><td>89</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][88];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][88];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][88];}?>"></td></tr>
													<tr><td>90</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][89];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][89];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][89];}?>"></td></tr>
													<tr><td>91</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][90];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][90];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][90];}?>"></td></tr>
													<tr><td>92</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][91];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][91];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][91];}?>"></td></tr>
													<tr><td>93</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][92];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][92];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][92];}?>"></td></tr>
													<tr><td>94</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][93];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][93];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][93];}?>"></td></tr>
													<tr><td>95</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][94];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][94];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][94];}?>"></td></tr>
													<tr><td>96</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][95];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][95];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][95];}?>"></td></tr>
													<tr><td>97</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][96];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][96];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][96];}?>"></td></tr>
													<tr><td>98</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][97];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][97];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][97];}?>"></td></tr>
													<tr><td>99</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][98];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][98];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][98];}?>"></td></tr>
													<tr><td>100</td> <td><input type="text" class="form-control" name="fname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['fname'][99];}?>"></td> <td><input type="text" class="form-control" name="mname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['mname'][99];}?>"></td> <td><input type="text" class="form-control" name="sname[]" value="<?php if(isset($success[2]) || isset($success[3]) || isset($success[4]) || isset($success[5]) || isset($success[6]) || isset($success[7]) || isset($success[8])){echo $_POST['sname'][99];}?>"></td></tr>
													
												</tbody>
											</table>
										</div>
									</div>
								</div>
							<!--end table -->
								<div class="row">
									<div class="col-md-3"></div>
									<div class="col-md-3">
										<div class="form-group">
											<label></label><br>
											<button type="submit" name="sv_stDiploma" class="btn btn-primary">Save</button>
										</div>
									</div>
								</div>
							</form>
						  </div>
						  <!-- /.tab-pane --> 
						  
					</div>
				</div>
			</div>
		</div>
    </section>
  </div>

<?php 
	include('footer/footer.php');
	include('footer/helpAdmin.php');
	include('footer/js.php');
?>